# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "build app and release to App Store."
  lane :release do |options|
    if options[:v]

       build_app(
	scheme: "DeliveryCheck",
        configuration: "Release"
      )

      upload_to_app_store(
        app_version: options[:v],
        submit_for_review: true,
        force: true,
        automatic_release: true,
        skip_screenshots: false,
        skip_metadata: false,
	submission_information: {
   		 export_compliance_uses_encryption: false
  	}
      )
    end
  end
end
