# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Build Test

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop  ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      
    - name: Set Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_16.app

    - name: Wait for Simulator to be ready
      run: xcrun simctl bootstatus ${{ env.UDID }} -b

    - name: Resolve Dependencies
      run: |
        rm -rf ~/Library/Developer/Xcode/DerivedData
        rm -rf ~/Library/Caches/org.swift.swiftpm
        rm -rf .swiftpm
        xcodebuild -resolvePackageDependencies
      working-directory: ./DeliveryCheck

    - name: Create config.xcconfig
      run: echo "${{ secrets.DEBUG_CONFIG }}" > ./DeliveryCheck/config.xcconfig

    - name: DeliveryCheck Build Tests
      run: |
        xcodebuild build \
          -project DeliveryCheck/DeliveryCheck.xcodeproj \
          -scheme DeliveryCheck \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
          CODE_SIGNING_ALLOWED=NO \
          -disablePackageRepositoryCache
